### ISSUE TITLE
Is it possible to build this repository?

### ISSUE THREAD

**Issue by kkk669** [holzschu/a-shell#109] opened 2020-09-24 21:50 UTC
I'm trying to build a-Shell, but it seems that this repository is currently impossible to build because of some problems.

The first problem is a conflict of dependencies. Specifically, both https://github.com/holzschu/Python-aux and https://github.com/holzschu/libssh2-for-iOS have openssl.framework, so Xcode outputs an error about that on build.

The second one is using paths like `/Users/holzschu/...` or `../../../Library/Developer/Xcode/DerivedData/...`. To avoid it, use their package's frameworks directly and don't have references to xcframework files. If the first problem is solved, I will be able to submit a PR to solve this if you want.

![Screen Shot 2020-09-25 at 6 43 15 AM](https://user-images.githubusercontent.com/601636/94203749-eaa23700-fefa-11ea-9b95-c6a3e5f2ba23.png)

Thanks.

**Comment by holzschu** [comment] 2020-09-25 10:34
Thanks for raising the issue. I'm working on it now. 
One of the changes is that Python-aux is not a Swift package anymore (which solves the first issue). Also, I moved from Python (which is Python 3.7) to cpython (a fork of the main python repository). 

I haven't figured out a way to automatically compile everything. Right now, to build, you would need:
```
git submodule update --init --recursive 
cd cpython
git checkout 3.9 # get branch 3.9 of the repository
sh ./downloadAndCompile.sh # compile all Python libraries and frameworks. Long enough for a coffee.
cd ..
```
After that, you should be able to compile a-Shell without further issues. I would like to move cpython to Swift packages distributed as binaries, but the number of frameworks involved (> 200 and counting) makes that difficult. Also, I am changing them every day at the moment.

**Comment by kkk669** [comment] 2020-09-25 10:46
Thanks for explaining the current status in detail. I'll wait for a while until those changes are done. Feel free to close this issue, and please let me know if there is anything I can do to help you.

**Comment by holzschu** [comment] 2020-10-31 15:17
Hi, 
I think the repository is now ready for building. I've updated all the sub-modules, and placed instructions in the Readme. 

It is not yet automatic (in the sense "open the project in Xcode and build"), but I don't know how to make it better.

**Comment by kkk669** [comment] 2020-11-08 14:20
Hi @holzschu,

Thanks for your working and a new instructions. I succeeded in building a-Shell. However, some modifications were required.

For example,

1. I had to delete all XCFrameworks except cpython, and instead, add their packages themselves into "Frameworks, Libraries, and Embedded Content".
    - There is [an issue related to code signing](https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/35) but it has been fixed in Xcode 12.2 and its Release Candidate (GM seed) was released recently so you can use it to submit to the App Store Connect.

    ![04FF5ECC-266F-44A4-A670-30502C3D01D3](https://user-images.githubusercontent.com/601636/98466787-195b3f00-2215-11eb-8019-c0012efbfe51.jpeg)

1. Because I use macOS Big Sur, I had to replace `macosx-10.15` with `macosx-11.0` in [`cpython/createModuleFrameworks.sh`](https://github.com/holzschu/cpython/blob/53ad3fc6619a694ea477b9012141f3e959344ac7/createModuleFrameworks.sh) and [`cpython/buildAllArchitectures.sh`](https://github.com/holzschu/cpython/blob/53ad3fc6619a694ea477b9012141f3e959344ac7/buildAllArchitectures.sh). (But I failed to build in the end)
1. `hterm_simulator.html` is required, but there is no such file in the repository, so I deleted it from Resources.

**Comment by holzschu** [comment] 2020-11-08 15:52
Thank you again for the detailed instructions. 
I have committed a version where the xcframeworks are added using the method you recommend, and without hterm_simulator.html (there was a period where the simulator did not have webAssembly, so I had to have a different `hterm.html` to run on the simulator). 

About the cpython building script: I need to change `macosx-10.15` with the actual system. Do you know where the building script failed?

**Comment by kkk669** [comment] 2020-11-08 16:16
Thank you for adopting my suggestion, but the commit 13eea6d30fbf4ee8c38bba2d26c7bd6301947042 looks different from what I expect. If my explanation is not clear enough, shall I submit a pull request?

> there was a period where the simulator did not have webAssembly, so I had to have a different hterm.html to run on the simulator

I see.

> Do you know where the building script failed?

Please could you wait for a while? I haven't been able to investigate about it well yet.

**Comment by kkk669** [comment] 2020-11-08 16:42
I created the pull request #128. I hope this is helpful. And if you find a problem, please let me know.

**Comment by kkk669** [comment] 2020-11-15 09:22
@holzschu 

> Do you know where the building script failed?

Installing of argon2 seems to be failed.

```console
$ sh ./buildAllArchitectures.sh
cp: /Users/kebo/a-shell/cpython/Library/lib/python3.9/site-packages/argon2/_ffi.abi3.so: No such file or directory
```

Here is my `make_install_osx.log`.

[make_install_osx.log](https://github.com/holzschu/a-shell/files/5542049/make_install_osx.log)

I looked into it and found some errors and warnings.

```
Header file /usr/include/ffi/ffi.h does not exist
building '_lzma' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -I./Include/internal -I./Include -I/Users/kebo/a-shell/cpython/Library/include -I. -I/usr/local/include -I/Users/kebo/a-shell/cpython/Include -I/Users/kebo/a-shell/cpython -c /Users/kebo/a-shell/cpython/Modules/_lzmamodule.c -o build/temp.macosx-11.0-x86_64-3.9/Users/kebo/a-shell/cpython/Modules/_lzmamodule.o
/Users/kebo/a-shell/cpython/Modules/_lzmamodule.c:16:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.
```

Maybe I need to install xz from Homebrew.

```
WARNING: Skipping argon2-cffi as it is not installed.
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL becaus
e the SSL module is not available.")': /simple/argon2-cffi/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL becaus
e the SSL module is not available.")': /simple/argon2-cffi/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL becaus
e the SSL module is not available.")': /simple/argon2-cffi/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL becaus
e the SSL module is not available.")': /simple/argon2-cffi/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL becaus
e the SSL module is not available.")': /simple/argon2-cffi/
Could not fetch URL https://pypi.org/simple/argon2-cffi/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): M
ax retries exceeded with url: /simple/argon2-cffi/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement argon2-cffi (from versions: none)
ERROR: No matching distribution found for argon2-cffi
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retri
es exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

I'm currently using the system's python3, so I'll retry after installing python3 from Homebrew.

**Comment by holzschu** [comment] 2020-11-15 09:38
I think the issue is just after the `lzma.h` error: 
```
Failed to build these modules:
_lzma                                                          


Could not build the ssl module!
Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
LibreSSL 2.6.4 and earlier do not provide the necessary APIs, https://github.com/libressl-portable/portable/issues/381
```
It seems you need to upgrade your OpenSSL library and headers.

**Comment by kkk669** [comment] 2020-11-15 10:26
Thank you.

> It seems you need to upgrade your OpenSSL library and headers.

I already have installed the latest openssl@1.1 from Homebrew, but it occurs. 🤔

On the other hand, I solved the `Header file /usr/include/ffi/ffi.h does not exist` error by running `xcode-select --install` to install the Command Line Tools, and solved the `fatal error: 'lzma.h' file not found` error by running `brew install xz` to install xz.

**Comment by kkk669** [comment] 2020-11-15 10:42
The reason might be probably that I didn't set the following environment variables. I'll try it.

```shell
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

**Comment by kkk669** [comment] 2021-02-04 15:02
@holzschu Awesome! I really appreciate your and @yury's work. I succeeded in building a-Shell without any hard modification but cpython. That has become way easier than before.

I used Xcode 12.3 and macOS 11.1.

My steps to build a-Shell:

1. **Clone the repo**
2. **Run `cd a-Shell && ./downloadFrameworks.sh`**
3. **Open `a-Shell.xcodeproj` in Xcode**
4. **Change Team, Bundle Identifier, App Groups and iCloud Containers into my own ones on the "Signing & Capabilities" settings of a-Shell, a-Shell-Intents, and a-Shell-IntentsUI**
5. (essentially unnecessary) Remove python-related frameworks from the "Frameworks, Libraries, and Embedded Content" section on the a-Shell target's General settings
6. (essentially unnecessary) Remove TeX-related resources from the "Copy Bundle Resources" section on the a-Shell target's "Build Phases" settings (to save time and effort to download these resources, sorry)
7. Add ios_system.xcframework to the "Frameworks and Libraries" section on the a-Shell-Intents' and a-Shell-IntentsUI's General settings
    - This is weird. I'll submit a PR later.
8. **Build and Run**

At first, I tried to build cpython with the following commands, but it failed. My output.log and all *.log files are attached below.

```shell
cd cpython
sh downloadAndCompile.sh > output.log 2>&1
```

[logs.zip](https://github.com/holzschu/a-shell/files/5926487/logs.zip)

**Comment by kkk669** [comment] 2021-03-21 17:14
> there is an old numpy directory in .../cpython/Library/lib/python3.9/site-packages/, and they interfere when python looks for numpy modules. In that case, erasing all the content of .../cpython/Library/lib/python3.9/site-packages/ could help.

You're right. Thank you so much.

And I was wrong. I should have installed the freetype that came with XQuartz, not Homebrew. The freetype of Homebrew will cause matplotlib to fail to build for iOS Simulator.

I've succeeded in building all XCFrameworks of cpython except for `python*_ios-PIL._imaging.xcframework`.

According to [make_ios.log](https://github.com/holzschu/a-shell/files/6177960/make_ios.log), it failed the following lines.

```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O3 -Wall -arch arm64 -miphoneos-version-min=14.0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -arch arm64 -miphoneos-version-min=14.0 -I/Users/kebo/a-shell/cpython -I/Users/kebo/a-shell/cpython/Frameworks_iphoneos/include/ -arch arm64 -miphoneos-version-min=14.0 -I/Users/kebo/a-shell/cpython -I/Users/kebo/a-shell/cpython/Frameworks_iphoneos/include/ -DHAVE_LIBJPEG -DHAVE_LIBZ -DHAVE_LIBTIFF -DPILLOW_VERSION="8.1.2" -I/Users/kebo/a-shell/cpython/Frameworks_iphoneos/include/freetype -I/usr/local/Cellar/jpeg/9d/include -I/Users/kebo/a-shell/cpython/packages/Pillow-8.1.2 -I/Users/kebo/a-shell/cpython -I/Users/kebo/a-shell/cpython/Frameworks_iphoneos/include -I/Users/kebo/a-shell/cpython/Library/include -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -I/usr/local/include -I/Users/kebo/a-shell/cpython/Library/include/python3.9 -c src/_imaging.c -o build/temp.macosx-11.2-arm64-3.9/src/_imaging.o
In file included from src/_imaging.c:87:                                                                                   
In file included from /Users/kebo/a-shell/cpython/Frameworks_iphoneos/include/tiffio.h:31:                                 
/Users/kebo/a-shell/cpython/Frameworks_iphoneos/include/tiff.h:28:10: fatal error: 'tiffconf.h' file not found             
#include "tiffconf.h"                                                                                                      
         ^~~~~~~~~~~~                                                                                                      
1 error generated.
```

**Comment by holzschu** [comment] 2021-03-21 17:57
Ah, that one is my fault. `tiffconf.h` should be in the `libtiff`xcframework, and I forgot to include it.
I'm going to fix it.

**Comment by holzschu** [comment] 2021-03-22 10:10
It should work now, if you re-download the xcframeworks.

**Comment by kkk669** [comment] 2021-03-22 17:38
I've succeeded in building all XCFrameworks of cpython. I also updated [my instruction](https://github.com/holzschu/a-shell/issues/109#issuecomment-794153545). I'm going to close this issue.

Finally, how about adding XQuartz (for matplotlib) and Node.js (for Jupyter Notebook)?

**Closed** 2021-03-26 11:52 UTC
