### ISSUE TITLE
BUG IOS App Crash Loop. Unable to Open.

### ISSUE THREAD

**Issue by DDay987** [holzschu/a-shell#402] opened 2022-04-18 04:01 UTC
Running latest version (1.8.6)
IPhone 6s
OS 14.8.1

I have reinstalled the app and rebooted my device with no success.

When I click the app on the home page it flashes like it is trying to open the app, but then immediately crashes back to the home screen. 
This process is repeatable / the app is not accessible.

**Comment by DDay987** [comment] 2022-04-18 04:07
As an additional update to this:

- The same issue _IS ALSO_ present in A-Shell mini
- This issue is _NOT_ present in Carnets.

**Comment by holzschu** [comment] 2022-04-18 07:01
Hi, 
this is probably the same issue that plagued Carnets (1.7.0): crashing on iOS 14 due to a bug in Xcode 13.3. 

The issue is supposed to be fixed in Xcode 13.3.1, so the next build should work but I cannot test it because I don't have an iOS 14 device. If you're interested, I can send you an invitation for a TestFlight build of a-Shell mini (the TestFlight build of a-Shell is still waiting for approval).

**Comment by holzschu** [comment] 2022-04-19 06:16
Thanks a lot.
a-Shell has now been approved for TestFlight: https://testflight.apple.com/join/WUdKe3f4 
But since I've received a report that the new build is, indeed, fixing the issue, I'm releasing it. It will be version 1.8.8 (to keep versions in sync between a-Shell and a-Shell mini)

**Comment by DDay987** [comment] 2022-04-19 15:13
I can confirm now that the testflight build of a-Shell (1.8.8) appears to be working as expected.

Thank you for all your work on this :) and your incredible apps.

**Closed** 2022-04-19 19:58 UTC
