### ISSUE TITLE
iphone

### ISSUE THREAD

**Issue by mamanngaga01** [holzschu/a-shell#358] opened 2022-01-03 08:43 UTC
If it is a long character string, it will be broken and cannot be processed.
Get and paste "dash" using shortcut variables!
How can I prevent line breaks without permission?
Manual input is okay.
"dash-11112222-3333-4444-5555-666677778888-0"

yt-dlp -f ”dash-11112222-3333-4444-5555-666677778888
-0
+ba” url

+ba not command

**Comment by holzschu** [comment] 2022-01-03 09:14
Hi, 
I'm not sure I understand the problem you are describing, or how to reproduce it in order to debug it. 

I assume you are developing a Shortcut, and are trying to get the input variable from a specific application or website (maybe the application or website is called dash?)

The first question is: is the input already broken when it arrives in the Shortcut (you can check it by displaying the variable from inside the Shortcut), or is it related to the transfer from the Shortcut to a-Shell. As far as I know, input strings are not processed before they reach a-Shell.

**Comment by mamanngaga01** [comment] 2022-01-03 14:59
Hi,

yt-dlp -F url >file.txt
awk @@@@ file.txt | sed @@@@ >dash

I got a single like this.
After that, I assigned it as a variable, but I couldn't.
I split the variable and assigned it to the dictionary and it worked fine.
However, a new problem arose here.
After that, it cannot be processed by a-shell.
The variable is displayed as is and is not executed.
So I created an a-shell-mini in the last process and it worked.
I don't know the cause.

**Comment by holzschu** [comment] 2022-01-03 15:56
Hi,
thanks for the more detailed explanation. I still have trouble understanding what you are trying to do, or what commands exactly you are running. If you can provide screenshots or code examples, it is easier for me to help.

From what I'm understanding, you are trying to parse the output of `yt-dlp`. After calling `awk` and `sed`, you get an output file named `dash`. I assume `dash` is a file, and it exists, and it contains what you want. 

Now, the question is "I assigned it as a variable, but I couldn't."  And there is, I think an issue: where and how are you assigning it as a variable? This seems to be the main question.

**Comment by mamanngaga01** [comment] 2022-01-09 22:53
Sorry I'm late.

"I assigned it as a variable, but I couldn't."
I'm sorry to forget how I did it.

Duplicate by putting the following in the shortcut.
Change the last process of the duplicated shortcut to "a-shell mini".
The command must be the same as the source.
It will not work if the process has the same "a-shell".

ios15.2
a-shell & a-shell mini
Manually create a folder, Folder name "tver".

https://www.icloud.com/shortcuts/940155d7611d4255a4aac8fda6f3eadb

sample
https://tver.jp/corner/f0093906

**Closed** 2022-01-15 03:52 UTC
