### ISSUE TITLE
`~/Documents/bin`: `#!sh`, `#!bc`, ... -> not executable

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#198] opened 2021-05-06 16:20 UTC
## Summary
 * `#!command_name` at the top of an executable text file seems to only work if `command_name` is `python` or `lua`.

## Expected Behavior

`~/Documents/bin/test1`:
```sh
#!sh
echo "It works"
```

or

```bc
#!bc
print 'a test'
```

or

```
#!almake_shell
# ^ Part of almost_make pip package

echo "It doesn't work"
```

`~/Documents/bin/test2`:
```py
#!python
print("It works")
```

```sh
$ chmod u+x ~/Documents/bin/test1
$ chmod u+x ~/Documents/bin/test2
$ test2
It works
$ test1
test1: command not found
```

`test1` and `test2` should produce the same output.

Thank you for your time!

**Comment by holzschu** [comment] 2021-05-06 16:51
Yes, that is currently the case. The offending lines are in `iOS_system`, file `iOS_system.m`, lines 2296-2316: 
https://github.com/holzschu/ios_system/blob/57e220e540c8da596b1331aeef27844f9ffd2b07/ios_system.m#L2296

I try to read the first line, infer if it is a scripting language and if so add it to the beginning of the command line.
The limited number of scripting languages has not been an issue until now, so thank you for raising that one. 

I think I could just take the last word of the first line, if it begins with "#!". It's not going to work with "#!sh", for the time being, but it will work with other shells.

**Comment by personalizedrefrigerator** [comment] 2021-05-06 17:55
I am not an ObjectiveC programmer, so this is probably partially wrong, but maybe,
```objc
    ... lua case ... (line 2311)
    } else {
        // Leave scriptName untouched.
        // Ref: https://stackoverflow.com/questions/11325951/how-to-split-a-string-of-words-and-add-to-an-array-objective-c
        NSArray* newArgs = [firstLine componentsSeparatedByString: @" "];
        int numNewArgs = [newArgs count];
        argc += numNewArgs + 1;
        argv = (char**) realloc(argv, sizeof(char*) * (argc));

        // Shift existing arguments
        for (int i = numNewArgs; i <= argc; i++) {
            argv[i] = argv[i - numNewArgs];
        }

        int i = 0;
        for (NSString* newArg in newArgs) {
            argv[i] = strdup(newArg.UTF8String);
            i++;
        }
        argv[i] = realloc(argv[i], locationName.length + 1);
        strcpy(argv[i], locationName.UTF8String);
        break;
    }

    if (scriptName) {
                                    // 2) insert script language at beginning of argument list
                                    argc += 1;
                                    argv = (char **)realloc(argv, sizeof(char*) * (argc + 1));
                                    // Move everything one step up
                                    for (int i = argc; i >= 1; i--) { argv[i] = argv[i-1]; }
                                    argv[1] = realloc(argv[1], locationName.length + 1);
                                    strcpy(argv[1], locationName.UTF8String);
                                    argv[0] = strdup(scriptName); // this one is new
                                    break;
    }
```

**Comment by holzschu** [comment] 2021-05-06 19:13
I've opted for something more extreme: 
```Objective-C
NSCharacterSet *invertedAlphaNumCharSet = [[NSCharacterSet alphanumericCharacterSet] invertedSet];
NSArray *components = [firstLine componentsSeparatedByCharactersInSet:invertedAlphaNumCharSet];
NSString *scriptNameString = components.lastObject;
```
The name of the script is the last word of the line, word being defined as "a set of alphanumeric characters". This works with `#!/any/path/to/perl`, `#!bc` and also `#! /usr/bin/env python`. It will fail if the language name contains a hyphen, though.

The only thing it does is add the name of the command in front of the file, so it does not work so well with `bc` and `sh`. But it should work with `almake_shell`. 

I'm uploading the new version now; it should be available for TestFlight in 24 to 36h.

**Comment by holzschu** [comment] 2021-05-07 05:47
The new build has been submitted for TestFlight, but I just realized: it's not going to be enough for `#!almake_shell`, since it's not a working command. I need to recurse here if the command does not exist.

**Comment by personalizedrefrigerator** [comment] 2021-05-07 17:33
Although 
```objc
NSCharacterSet *invertedAlphaNumCharSet = [[NSCharacterSet alphanumericCharacterSet] invertedSet];
NSArray *components = [firstLine componentsSeparatedByCharactersInSet:invertedAlphaNumCharSet];
NSString *scriptNameString = components.lastObject;
```

works for commands like `almake_shell` and `bc`, it won't work for commands like `#!bc -l`...

**Comment by holzschu** [comment] 2021-05-07 18:58
Ah, yes. It's going to be difficult to have a regex that matches both `/usr/bin/env python` and `bc -l` (or `/usr/bin/env bc -l`).
This needs more thinking.

**Comment by personalizedrefrigerator** [comment] 2021-05-08 13:23
It looks like build 155 broke ipython. See #204.

**Comment by holzschu** [comment] 2021-05-13 08:26
Build 157 has improved on the shebang analysis: all arguments are transferred to the beginning of the command line, so "#! bc -f" works now. "#!almake_shell" wont't work, because we don't loop back to the beginning to parse the new command if it's a file, but I think "#!python almake_shell" might work.

"#!sh" of course still won't work. I'm also not fully satisfied with the treatment of "python": to make it work with "python3.9", everything that contains the string "python" is remapped to "python", but that seems like too much, and something that will create issues later.

**Closed** 2021-05-26 21:05 UTC
Labels: fix committed

**Comment by personalizedrefrigerator** [comment] 2021-06-05 19:46
`#!python -m almost_make.utils.shellUtil.interactiveShell
...
`
is working!

**Comment by holzschu** [comment] 2021-06-05 20:25
That's great!
Does that mean that there could be a way to execute small shell scripts?

**Comment by ifuchs** [comment] 2022-03-02 23:13
I have a python script which I have set to executable using chmod. The first line of the script says #!python. However when I try to run it by typing the file name I am getting command not found. Should this work?

**Comment by personalizedrefrigerator** [comment] 2022-03-03 04:49
> I have a python script which I have set to executable using chmod. The first line of the script says #!python. However when I try to run it by typing the file name I am getting command not found. Should this work?

Is the python script in `~/Documents/bin`? Does it show up as executable when you run `ls -l path/to/script`?

**Comment by holzschu** [comment] 2022-03-03 06:59
You're right, I can reproduce this issue, and it should work (I'm also pretty sure it did). I'll have a look.

**Comment by ifuchs** [comment] 2022-03-03 12:13
I have #!  python on the first line and an ls shows it is executable but it doesn’t work. And yes the .py file is in the documents directory.  Must be something elese

**Comment by ifuchs** [comment] 2022-03-03 12:30
My .py file is in the documents/bin directory and it is set to executable. It has 
#! python on the first line. Nevertheless it is not working. Is there something else?

**Comment by ifuchs** [comment] 2022-03-03 13:14
I stand corrected. It does work (there was a spurious blank line at the beginning of the file). However command completion does not work for this file. Should it?

**Comment by ifuchs** [comment] 2022-03-03 15:26
I had restarted it and still had the problem but I think I understand why. If I type the first few letters of the command and then hit tab for command completion I am getting a different command and I am not being shown any alternatives. If I type enough characters so that the command name is unambiguous and then hit tab, I get the command I’m looking for. Specifically, my command is wordleai.py and if I type word+tab, I get wordcloud.cli.

**Comment by holzschu** [comment] 2022-03-03 15:28
Tab shows the first match, but you can use the arrows to scroll through the other possible matches (or, as you did, type more letters)

**Comment by ifuchs** [comment] 2022-03-04 14:50
OK, it works except for one thing. If I type part of the command and then hit tab, the full name is filled in, but when I hit return I always get "command not found" BUT only the first time after starting ashell. Every subsequent attempt works fine.
