### ISSUE TITLE
Long shell commands: input not wrapping

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#202] opened 2021-05-08 12:05 UTC
https://user-images.githubusercontent.com/46334387/117538317-83815080-afba-11eb-93e2-167b89bf199e.MP4

## Steps to reproduce
 * Enter a long command
   * For example `$ echo This is a long command, at some point, I expect this to word-wrap at the end of the line, but it doesn't`

## Expected behavior
 * Entered text should wrap.

## Observed behavior
 * Entered text does not wrap, but input is still accumulated (and not shown in the terminal).

## Version information
 * Build 156 (TestFlight)

**Comment by personalizedrefrigerator** [comment] 2021-05-08 12:08
It looks like wraparound is enabled...

https://github.com/holzschu/a-shell/blob/e9dba50bb2e8d7c7960dfacc51185ee004ebf965/hterm.html#L476-L480

**Comment by personalizedrefrigerator** [comment] 2021-05-08 12:16
It looks like there are several new versions of `hterm` available...

## See 
 * https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/doc/ChangeLog.md
 * https://github.com/chromium/hterm

**Comment by holzschu** [comment] 2021-05-30 13:47
I can reproduce the issue. What is really strange is that if I add text to the begining of the line, it does wrap around.

**Comment by holzschu** [comment] 2021-06-03 18:00
The issue is fixed in build 164. It also fixes pasting of long lines.

**Comment by personalizedrefrigerator** [comment] 2021-06-04 17:07
I'm not seeing build 164 in TestFlight yet. I'll close this after testing with build ≥ 164.
Thank you for fixing this!

**Comment by holzschu** [comment] 2021-06-04 19:02
Yes, it's still in the process of being approved. The first build of a new version takes longer to be approved. After that, all future builds within the same version are approved immediately. Since I just sent version 1.7.2/build 163 to the AppStore (the list of changes was getting too long), 164 is the first build of version 1.7.3.

**Closed** 2021-06-05 03:25 UTC
Labels: fix committed
