### ISSUE TITLE
[iOS/iPadOS 15] Hide QuckType bar

### ISSUE THREAD

**Issue by kkk669** [holzschu/a-shell#319] opened 2021-10-03 17:24 UTC
In iOS/iPadOS 15, a-Shell displays the QuickType bar on the bottom.

![F3A6C905-453A-47AF-B6F6-55C6BBAD7F3B](https://user-images.githubusercontent.com/601636/135764772-4d201cb1-f1d5-475c-9c17-b62a7832463e.png)

If I remember correctly, it was hidden in iOS/iPadOS 14.x and earlier.

Maybe, it relates to [this](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-15-release-notes):

> In iOS 14 and iPadOS 14 and earlier, when autocorrectionType is set to UITextAutocorrectionTypeNo, the QuickType bar is disabled. For apps linked against iOS 15 and iPadOS 15 or later, the QuickType bar is enabled and shows spellchecking candidates. If the new behavior isn’t desirable for your use case, set spellCheckingType to UITextSpellCheckingTypeNo to hide the QuickType bar. (68874861)

**Comment by holzschu** [comment] 2021-10-03 19:33
That's strange: I don't have this bar on my iPad (running iPadOS 15.0), with all the different keyboards I could try.

A WkWebView does not have the spellCheckingType property, so the advice on the linked page does not work. I'll keep investigating.

**Comment by kkk669** [comment] 2021-10-03 19:51
My environment:

- 12.9-inch iPad Pro 5th generation
- iPadOS 15.1 Developer Beta 2
- a-Shel 1.7.6 (194)
- Keyboard settings:
  - ![F68F4F0D-D83A-4C9F-8B47-35EBAC803FAD](https://user-images.githubusercontent.com/601636/135769308-27823b0b-ca20-43bf-8422-86770dc59162.png)

**Comment by kkk669** [comment] 2021-10-05 13:24
@holzschu It seems that you can't reproduce the problem if the Auto-Correction is disabled, so please check it.

![AFF64A00-E841-4D39-86D5-E317628346DC](https://user-images.githubusercontent.com/601636/136031166-55762f11-e026-4fff-a6b7-9538296d27ab.jpeg)

**Comment by kkk669** [comment] 2021-10-05 16:33
I believe that we need this workaround.

- https://github.com/blinksh/blink/commit/0e18174d99a23ea53daa6abfdf84b189a2b36c80
- https://bugs.webkit.org/show_bug.cgi?id=230360

**Comment by holzschu** [comment] 2021-10-05 17:02
Impressive workaround. I'll add it to a-Shell.

**Comment by holzschu** [comment] 2021-10-06 08:11
Quick update: I still cannot reproduce the issue on my end, with or without Auto-Correction disabled. I have copied the workaround you linked into a-Shell, and it does not break at compilation or execution. It will be in build 197. If it works, I'll try to convert the objective-C code to Swift.

**Comment by kkk669** [comment] 2021-10-06 14:00
> I still cannot reproduce the issue on my end, with or without Auto-Correction disabled.

Hmm, that's strange. After small tests, I found that the problem is depending on what keyboard I'm using. For instance, I can reproduce it when using "English (US)" keyboard, but can't when using "Japanese - Romaji" keyboard.

> I have copied the workaround you linked into a-Shell, and it does not break at compilation or execution. It will be in build 197. If it works, I'll try to convert the objective-C code to Swift.

Thank you.

**Comment by holzschu** [comment] 2021-10-07 15:52
Here you are, and thanks for the help. The repository is behind the distributed version, but it should be working.
[Archive.zip](https://github.com/holzschu/a-shell/files/7305157/Archive.zip)

**Comment by kkk669** [comment] 2021-10-07 16:12
Thank you so much. If I find a workaround that works, I'll send a PR.

**Comment by kkk669** [comment] 2021-10-10 12:06
Hi @holzschu, I've confirmed that the workaround would works well, so I sent a PR #324.

**Closed** 2021-10-11 18:34 UTC
